# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'routine_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EMS(object):
    def setupUi(self, EMS):
        EMS.setObjectName(_fromUtf8("EMS"))
        EMS.resize(1030, 629)
        EMS.setSizeIncrement(QtCore.QSize(19, 567))
        EMS.setWindowFilePath(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(EMS)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.ivn_sb = QtGui.QLineEdit(self.centralwidget)
        self.ivn_sb.setObjectName(_fromUtf8("ivn_sb"))
        self.verticalLayout_6.addWidget(self.ivn_sb)
        self.ivn = QtGui.QTableWidget(self.centralwidget)
        self.ivn.setAlternatingRowColors(True)
        self.ivn.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.ivn.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.ivn.setTextElideMode(QtCore.Qt.ElideRight)
        self.ivn.setGridStyle(QtCore.Qt.NoPen)
        self.ivn.setObjectName(_fromUtf8("ivn"))
        self.ivn.setColumnCount(0)
        self.ivn.setRowCount(0)
        self.verticalLayout_6.addWidget(self.ivn)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.time_label = QtGui.QLabel(self.centralwidget)
        self.time_label.setObjectName(_fromUtf8("time_label"))
        self.horizontalLayout.addWidget(self.time_label)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self.user_label = QtGui.QLabel(self.centralwidget)
        self.user_label.setObjectName(_fromUtf8("user_label"))
        self.horizontalLayout_2.addWidget(self.user_label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_3.addWidget(self.label_9)
        self.garbage = QtGui.QLabel(self.centralwidget)
        self.garbage.setObjectName(_fromUtf8("garbage"))
        self.horizontalLayout_3.addWidget(self.garbage)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.c_name = QtGui.QLabel(self.centralwidget)
        self.c_name.setObjectName(_fromUtf8("c_name"))
        self.gridLayout.addWidget(self.c_name, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.due_label = QtGui.QLabel(self.centralwidget)
        self.due_label.setObjectName(_fromUtf8("due_label"))
        self.gridLayout.addWidget(self.due_label, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.cart = QtGui.QTableWidget(self.centralwidget)
        self.cart.setObjectName(_fromUtf8("cart"))
        self.cart.setColumnCount(0)
        self.cart.setRowCount(0)
        self.verticalLayout.addWidget(self.cart)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.total_amt = QtGui.QLabel(self.centralwidget)
        self.total_amt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.total_amt.setObjectName(_fromUtf8("total_amt"))
        self.horizontalLayout_5.addWidget(self.total_amt)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.clear_item = QtGui.QPushButton(self.centralwidget)
        self.clear_item.setObjectName(_fromUtf8("clear_item"))
        self.horizontalLayout_4.addWidget(self.clear_item)
        self.clear_cart = QtGui.QPushButton(self.centralwidget)
        self.clear_cart.setObjectName(_fromUtf8("clear_cart"))
        self.horizontalLayout_4.addWidget(self.clear_cart)
        self.update = QtGui.QPushButton(self.centralwidget)
        self.update.setObjectName(_fromUtf8("update"))
        self.horizontalLayout_4.addWidget(self.update)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout_2.addWidget(self.radioButton_2, 1, 0, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.centralwidget)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout_2.addWidget(self.radioButton, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.chk_out = QtGui.QPushButton(self.centralwidget)
        self.chk_out.setObjectName(_fromUtf8("chk_out"))
        self.verticalLayout_2.addWidget(self.chk_out)
        self.due_self = QtGui.QPushButton(self.centralwidget)
        self.due_self.setObjectName(_fromUtf8("due_self"))
        self.verticalLayout_2.addWidget(self.due_self)
        self.print_recipt = QtGui.QPushButton(self.centralwidget)
        self.print_recipt.setObjectName(_fromUtf8("print_recipt"))
        self.verticalLayout_2.addWidget(self.print_recipt)
        self.clr = QtGui.QPushButton(self.centralwidget)
        self.clr.setObjectName(_fromUtf8("clr"))
        self.verticalLayout_2.addWidget(self.clr)
        self.exit = QtGui.QPushButton(self.centralwidget)
        self.exit.setObjectName(_fromUtf8("exit"))
        self.verticalLayout_2.addWidget(self.exit)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 2, 1, 1)
        EMS.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(EMS)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1030, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        EMS.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(EMS)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        EMS.setStatusBar(self.statusbar)

        self.retranslateUi(EMS)
        QtCore.QMetaObject.connectSlotsByName(EMS)

    def retranslateUi(self, EMS):
        EMS.setWindowTitle(_translate("EMS", "EMS Custom | Routine Operations ", None))
        self.label.setText(_translate("EMS", "Search the Inventory", None))
        self.ivn_sb.setPlaceholderText(_translate("EMS", "Try Red...", None))
        self.ivn.setSortingEnabled(True)
        self.label_7.setText(_translate("EMS", "Time:", None))
        self.time_label.setText(_translate("EMS", "Monday", None))
        self.label_8.setText(_translate("EMS", "User:", None))
        self.user_label.setText(_translate("EMS", "Kallu", None))
        self.label_9.setText(_translate("EMS", "Total:", None))
        self.garbage.setText(_translate("EMS", "50", None))
        self.label_2.setText(_translate("EMS", "Select Customer", None))
        self.label_3.setText(_translate("EMS", "Customer Name:", None))
        self.c_name.setText(_translate("EMS", "General", None))
        self.label_5.setText(_translate("EMS", "Payment Due:", None))
        self.due_label.setText(_translate("EMS", "0.0", None))
        self.label_6.setText(_translate("EMS", "Total", None))
        self.total_amt.setText(_translate("EMS", "0.0", None))
        self.clear_item.setText(_translate("EMS", "Clear Item", None))
        self.clear_cart.setText(_translate("EMS", "Clear Cart", None))
        self.update.setText(_translate("EMS", "Update", None))
        self.label_4.setText(_translate("EMS", "Rate:", None))
        self.radioButton_2.setText(_translate("EMS", "Whole Sale", None))
        self.radioButton.setText(_translate("EMS", "Retail", None))
        self.chk_out.setText(_translate("EMS", "Check Out", None))
        self.due_self.setText(_translate("EMS", "Due / Self", None))
        self.print_recipt.setText(_translate("EMS", "Print Recipt", None))
        self.clr.setText(_translate("EMS", "Clear", None))
        self.exit.setText(_translate("EMS", "Exit", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    EMS = QtGui.QMainWindow()
    ui = Ui_EMS()
    ui.setupUi(EMS)
    EMS.show()
    sys.exit(app.exec_())

